function supergrouppathmatrix = function_import_super_group_path_matrix(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SUPERGROUPPATHMATRIX = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  SUPERGROUPPATHMATRIX = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  supergrouppathmatrix = importfile("/home/matt/gits/bate-scan/analysis_3/analysis3a/super_group_path_matrix.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Feb-2024 15:17:50

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 25);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["subj", "ability", "face", "fame", "angle", "trial", "rt", "acc", "sq", "iaseq", "s001", "s002", "s003", "s004", "s005", "s006", "s007", "s008", "s009", "s010", "s011", "s012", "s013", "s014", "s015"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "categorical", "categorical", "double", "double", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["subj", "ability", "face", "fame", "angle", "acc", "sq", "iaseq", "s001", "s002", "s003", "s004", "s005", "s006", "s007", "s008", "s009", "s010", "s011", "s012", "s013", "s014", "s015"], "EmptyFieldRule", "auto", ...
    'TreatAsMissing', {'x', 'NA'}, 'FillValue', categorical(NaN));

% Import the data
supergrouppathmatrix = readtable(filename, opts);

end